rules:

  ## based on eslint v4.0.0
  ## Comment out all the recommended rules with '#'

  ## Possible Errors

  for-direction: off
  no-await-in-loop: off
  no-compare-neg-zero: off
  #no-cond-assign: error
  #no-console: error
  #no-constant-condition: error
  #no-control-regex: error
  #no-debugger: error
  #no-dupe-args: error
  #no-dupe-keys: error
  #no-duplicate-case: error
  #no-empty: error
  #no-empty-character-class: error
  #no-ex-assign: error
  #no-extra-boolean-cast: error
  no-extra-parens: off
  #no-extra-semi: error
  #no-func-assign: error
  #no-inner-declarations: error
  #no-invalid-regexp: error
  #no-irregular-whitespace: error
  #no-obj-calls: error
  no-prototype-builtins: off
  #no-regex-spaces: error
  #no-sparse-arrays: error
  no-template-curly-in-string: off
  #no-unexpected-multiline: error
  #no-unreachable: error
  #no-unsafe-finally: error
  no-unsafe-negation: off
  #use-isnan: error
  valid-jsdoc: off
  #valid-typeof: error

  ## Best Practices

  accessor-pairs: off
  array-callback-return: off
  block-scoped-var: off
  class-methods-use-this: off
  complexity: off
  consistent-return: off
  curly: off
  default-case: off
  dot-location: off
  dot-notation: off
  eqeqeq: off
  guard-for-in: off
  no-alert: off
  no-caller: off
  #no-case-declarations: error
  no-div-regex: off
  no-else-return: off
  no-empty-function: off
  #no-empty-pattern: error
  no-eq-null: off
  no-eval: off
  no-extend-native: off
  no-extra-bind: off
  no-extra-label: off
  #no-fallthrough: error
  no-floating-decimal: off
  no-global-assign: off
  no-implicit-coercion: off
  no-implicit-globals: off
  no-implied-eval: off
  no-invalid-this: off
  no-iterator: off
  no-labels: off
  no-lone-blocks: off
  no-loop-func: off
  no-magic-numbers: off
  no-multi-spaces: off
  no-multi-str: off
  no-new: off
  no-new-func: off
  no-new-wrappers: off
  #no-octal: error
  no-octal-escape: off
  no-param-reassign: off
  no-proto: off
  #no-redeclare: error
  no-return-assign: off
  no-return-await: off
  no-script-url: off
  #no-self-assign: error
  no-self-compare: off
  no-sequences: off
  no-throw-literal: off
  no-unmodified-loop-condition: off
  no-unused-expressions: off
  #no-unused-labels: error
  no-useless-call: off
  no-useless-concat: off
  no-useless-escape: off
  no-useless-return: off
  no-void: off
  no-warning-comments: off
  no-with: off
  prefer-promise-reject-errors: off
  radix: off
  require-await: off
  vars-on-top: off
  wrap-iife: off
  yoda: off

  ## Strict Mode

  strict: off

  ## Variables

  init-declarations: off
  no-catch-shadow: off
  #no-delete-var: error
  no-label-var: off
  no-restricted-globals: off
  no-shadow: off
  no-shadow-restricted-names: off
  #no-undef: error
  no-undef-init: off
  no-undefined: off
  #no-unused-vars: error
  no-use-before-define: off

  ## Node.js and CommonJS

  callback-return: off
  global-require: off
  handle-callback-err: off
  no-buffer-constructor: off
  no-mixed-requires: off
  no-new-require: off
  no-path-concat: off
  no-process-env: off
  no-process-exit: off
  no-restricted-modules: off
  no-restricted-properties: off
  no-sync: off

  ## Stylistic Issues

  array-bracket-newline: off
  array-bracket-spacing: off
  array-element-newline: off
  block-spacing: off
  brace-style: off
  camelcase: off
  capitalized-comments: off
  comma-spacing: off
  comma-dangle: off
  comma-style: off
  computed-property-spacing: off
  consistent-this: off
  eol-last: off
  func-call-spacing: off
  func-name-matching: off
  func-names: off
  func-style: off
  id-blacklist: off
  id-length: off
  id-match: off
  indent: off
  jsx-quotes: off
  key-spacing: off
  keyword-spacing: off
  line-comment-position: off
  linebreak-style: off
  lines-around-comment: off
  max-depth: off
  max-len: off
  max-lines: off
  max-nested-callbacks: off
  max-params: off
  max-statements-per-line: off
  max-statements: off
  multiline-ternary: off
  new-cap: off
  new-parens: off
  newline-per-chained-call: off
  no-array-constructor: off
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-lonely-if: off
  no-mixed-operators: off
  #no-mixed-spaces-and-tabs: error
  no-multi-assign: off
  no-multiple-empty-lines: off
  no-negated-condition: off
  no-nested-ternary: off
  no-new-object: off
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: off
  no-ternary: off
  no-trailing-spaces: off
  no-underscore-dangle: off
  no-unneeded-ternary: off
  no-whitespace-before-property: off
  nonblock-statement-body-position: off
  object-curly-newline: off
  object-curly-spacing: [off, never]
  object-property-newline: off
  one-var: off
  one-var-declaration-per-line: off
  operator-assignment: off
  operator-linebreak: off
  padded-blocks: off
  padding-line-between-statements: off
  quote-props: off
  quotes: off
  require-jsdoc: off
  semi: off
  semi-spacing: off
  semi-style: off
  sort-keys: off
  sort-vars: off
  space-before-blocks: off
  space-before-function-paren: off
  space-in-parens: off
  space-infix-ops: off
  space-unary-ops: off
  spaced-comment: off
  switch-colon-spacing: off
  template-tag-spacing: off
  unicode-bom: off
  wrap-regex: off

  ## ECMAScript 6

  arrow-body-style: off
  arrow-parens: off
  arrow-spacing: off
  #constructor-super: error
  generator-star-spacing: off
  #no-class-assign: error
  no-confusing-arrow: off
  #no-const-assign: error
  #no-dupe-class-members: error
  no-duplicate-imports: off
  #no-new-symbol: error
  no-restricted-imports: off
  #no-this-before-super: error
  no-useless-computed-key: off
  no-useless-constructor: off
  no-useless-rename: off
  no-var: off
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-const: off
  prefer-destructuring: off
  prefer-numeric-literals: off
  prefer-reflect: off
  prefer-rest-params: off
  prefer-spread: off
  prefer-template: off
  #require-yield: error
  rest-spread-spacing: off
  sort-imports: off
  symbol-description: off
  template-curly-spacing: off
  yield-star-spacing: off
